### PR TITLE
Added mask process

### PR DESCRIPTION
**Pull request by clausmichele**
xArray based mask process has been added. Tests are passing. @ValentinaHutter let me know if you can deploy it to the dev endpoint so that I can test it via openEO.

### CODE REVIEW

**Comment by clausmichele** [comment]
Before being able to use it via openEO, there is something to fix in openeo-odc, since now it translates the graph in this form:
`_5_11 = oeop.mask(**{'data': _4_3, 'mask': '_3_2'})`
instead of:
`_5_11 = oeop.mask(**{'data': _4_3, 'mask': _3_2})`

The 'mask' parameter is not mapped correctly.

**Comment by ValentinaHutter** [comment]
Thanks for adding that, I will have a look at the change we need in openeo-odc and then update you again, when I have it in the dev endpoint!

**Comment by ValentinaHutter** [comment]
Okay, I just had a look at the Mask process again... I had implemented it before, but in the arrays file: https://github.com/Open-EO/openeo-processes-python/blob/master/src/openeo_processes/arrays.py#L1410
therefore you found a test in the https://github.com/Open-EO/openeo-processes-python/blob/master/tests/test_arrays.py#L190

anyway, I have to make the small change in the openeo-odc, then I will update you again on it :)

**Comment by clausmichele** [comment]
I didn't know it was already there! I did not check carefully because from here https://github.com/openEOPlatform/architecture-docs/issues/73 I supposed it was not implemented yet. Maybe you can just add the exceptions with the informative messages to your version and discard this pull request?

**Comment by ValentinaHutter** [comment]
yes, I'm sorry for that, it had just been put in the wrong file before, as it should be in the cubes.py (where you added it), but I will compare the implementations and put it in the cubes...

**Comment by ValentinaHutter** [comment]
The mask processes is now available on dev and will be on prod with the next update (in the next few days). Thanks again for providing a version of the process, I will now close this PR. :)

**Pull request closed without merging**
